# Air live reload configuration
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o tmp/server main.go"
bin = "tmp/server"
full_bin = "tmp/server"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "tmp", "data"]
delay = 500 # ms

[log]
time = true

[color]
main = "cyan"